language: node_js

node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run dev -- --silent &  
script:
  - $(npm bin)/cypress run --record